"""zone and country addition

Revision ID: 0aaed4e2832f
Revises: b5bc350c3df1
Create Date: 2023-08-03 16:18:29.056289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aaed4e2832f'
down_revision = 'b5bc350c3df1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ZoneID', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'zone', ['ZoneID'], ['ZoneID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ZoneID')

    # ### end Alembic commands ###
