"""schema update

Revision ID: 1fa72c55c6c0
Revises: 76d380001ff4
Create Date: 2023-08-09 11:11:24.059075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fa72c55c6c0'
down_revision = '76d380001ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliation', schema=None) as batch_op:
        batch_op.drop_constraint('affiliation_ibfk_1', type_='foreignkey')
        batch_op.drop_column('CountryID')

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CountryID', sa.Integer(), nullable=True))
        batch_op.alter_column('AffiliationName',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
        batch_op.drop_constraint('person_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'person', ['ManagerID'], ['PersonID'])
        batch_op.create_foreign_key(None, 'country', ['CountryID'], ['CountryID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('person_ibfk_1', 'person', ['ManagerID'], ['PersonID'], ondelete='SET NULL')
        batch_op.alter_column('AffiliationName',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_column('CountryID')

    with op.batch_alter_table('affiliation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CountryID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('affiliation_ibfk_1', 'country', ['CountryID'], ['CountryID'])

    # ### end Alembic commands ###
