"""deletion of tests

Revision ID: 2ec87fba6544
Revises: a8e6d89f313d
Create Date: 2023-08-15 13:42:50.440059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec87fba6544'
down_revision = 'a8e6d89f313d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliation', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'affiliation', ['ParentAffiliation'], ['AffiliationID'], ondelete='SET NULL')

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('AffiliationID', sa.String(length=256), nullable=True))
        batch_op.create_foreign_key(None, 'affiliation', ['AffiliationID'], ['AffiliationID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('AffiliationID')

    with op.batch_alter_table('affiliation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
