"""addition of time

Revision ID: 49d160ba510b
Revises: 9735d40acd9f
Create Date: 2023-08-21 10:37:44.643853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d160ba510b'
down_revision = '9735d40acd9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time',
    sa.Column('Date', sa.Date(), nullable=False),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('Month', sa.Integer(), nullable=True),
    sa.Column('Day', sa.Integer(), nullable=True),
    sa.Column('Week', sa.Integer(), nullable=True),
    sa.Column('Weekday', sa.String(length=10), nullable=True),
    sa.Column('Quarter', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time')
    # ### end Alembic commands ###
