"""added affiliation

Revision ID: 51da361f161a
Revises: 4cc1607af8f4
Create Date: 2023-08-07 14:11:28.534065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51da361f161a'
down_revision = '4cc1607af8f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliation',
    sa.Column('AffiliationName', sa.String(length=256), nullable=False),
    sa.Column('CountryID', sa.Integer(), nullable=False),
    sa.Column('ParentAffiliation', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['CountryID'], ['country.CountryID'], ),
    sa.ForeignKeyConstraint(['ParentAffiliation'], ['affiliation.AffiliationName'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('AffiliationName')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('affiliation')
    # ### end Alembic commands ###
