"""addition of roles attributes

Revision ID: 7348009ac28f
Revises: 49d160ba510b
Create Date: 2023-08-28 09:20:48.099740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7348009ac28f'
down_revision = '49d160ba510b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Status', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('JoinDate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('LeaveDate', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('LeaveDate')
        batch_op.drop_column('JoinDate')
        batch_op.drop_column('Status')

    # ### end Alembic commands ###
