"""added affiliation2

Revision ID: 76d380001ff4
Revises: 51da361f161a
Create Date: 2023-08-07 14:12:34.698670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d380001ff4'
down_revision = '51da361f161a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('AffiliationName', sa.String(length=256), nullable=False))
        batch_op.create_foreign_key(None, 'affiliation', ['AffiliationName'], ['AffiliationName'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('AffiliationName')

    # ### end Alembic commands ###
