"""Added attendance model

Revision ID: 860559aa27bc
Revises: 7dca07fd8788
Create Date: 2023-08-03 11:41:25.965841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860559aa27bc'
down_revision = '7dca07fd8788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('AttendanceID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PersonID', sa.Integer(), nullable=True),
    sa.Column('MeetingID', sa.Integer(), nullable=True),
    sa.Column('AttendanceDuration', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['MeetingID'], ['meeting.MeetingID'], ),
    sa.ForeignKeyConstraint(['PersonID'], ['person.PersonID'], ),
    sa.PrimaryKeyConstraint('AttendanceID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    # ### end Alembic commands ###
