"""addition of parent affiliation id

Revision ID: 9735d40acd9f
Revises: e10aa68913fa
Create Date: 2023-08-17 11:16:30.498731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9735d40acd9f'
down_revision = 'e10aa68913fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ParentAffiliationID', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('ParentAffiliationName', sa.String(length=256), nullable=True))
        batch_op.drop_constraint('affiliation_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'affiliation', ['ParentAffiliationID'], ['AffiliationID'], ondelete='SET NULL')
        batch_op.drop_column('ParentAffiliation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ParentAffiliation', mysql.VARCHAR(length=256), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('affiliation_ibfk_1', 'affiliation', ['ParentAffiliation'], ['AffiliationID'], ondelete='SET NULL')
        batch_op.drop_column('ParentAffiliationName')
        batch_op.drop_column('ParentAffiliationID')

    # ### end Alembic commands ###
