"""schema update3

Revision ID: a8e6d89f313d
Revises: d16483c8d3b9
Create Date: 2023-08-09 14:37:28.918762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8e6d89f313d'
down_revision = 'd16483c8d3b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persontestcsv', schema=None) as batch_op:
        batch_op.alter_column('AffiliationName',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
        batch_op.drop_constraint('persontestcsv_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'affiliation', ['AffiliationName'], ['AffiliationName'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persontestcsv', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('persontestcsv_ibfk_2', 'affiliation', ['AffiliationName'], ['AffiliationName'])
        batch_op.alter_column('AffiliationName',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)

    # ### end Alembic commands ###
