"""initial migration

Revision ID: b05171598cad
Revises: 
Create Date: 2023-07-14 11:12:51.419877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05171598cad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint('person_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'person', ['ManagerID'], ['PersonID'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('person_ibfk_1', 'person', ['ManagerID'], ['PersonID'])

    # ### end Alembic commands ###
