"""zone and country addition

Revision ID: b5bc350c3df1
Revises: 860559aa27bc
Create Date: 2023-08-03 16:17:58.059089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5bc350c3df1'
down_revision = '860559aa27bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone',
    sa.Column('ZoneID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ZoneName', sa.String(length=256), nullable=True),
    sa.Column('Timezone', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('ZoneID')
    )
    op.create_table('country',
    sa.Column('CountryID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ZoneID', sa.Integer(), nullable=True),
    sa.Column('CountryName', sa.String(length=256), nullable=True),
    sa.Column('Alpha2Code', sa.String(length=2), nullable=True),
    sa.Column('Alpha3Code', sa.String(length=3), nullable=True),
    sa.Column('PhonePrefix', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ZoneID'], ['zone.ZoneID'], ),
    sa.PrimaryKeyConstraint('CountryID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country')
    op.drop_table('zone')
    # ### end Alembic commands ###
